development:
  adapter: postgresql
  host: localhost
  username: erickatz
  database: simple_cms_dev


test:
  adapter: postgresql
  host: localhost
  username: erickatz
  database: simple-cms-test

production:
  adapter: postgresql
  encoding: unicode
  database: simple-cms
